[package]
name = "rusoto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
rusoto_core = "0.48.0"
rusoto_dynamodb = "0.48.0"
tokio = { version = "1.27.0", features = ["full"] }
