[package]
name = "aws-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.52.0"
aws-sdk-dynamodb = "0.22.0"
dotenv = "0.15.0"
tokio = { version = "1.23.0", features = ["full"] }
